#!/bin/bash
# Build a script that takes a user's input as a sentence and then reverses the sentence word by word (e.g., "Hello World" becomes "World Hello").

read -p "Enter a sentence: " sentence
reversed_sentence=$(echo $sentence | awk '{
    for (i=NF; i>1; i--) {
        printf "%s ", $i;
    }
    print $1
}')
echo "$reversed_sentence"